import 'package:flutter/material.dart';
const Color kMainColor=Color(0XFF7F3DFF);
const Color kLightgrey=Color(0XFFEEEEEE);
const Color kGrey=Color(0XFF91919F);
const Color kWhite=Color(0XFFFFFFFF);
const Color kBlack=Color(0XFF000000);
const Color kGreen=Color(0XFF00A86B);
const Color kRed=Color(0XFFF03C4A);
const Color kYellow=Color(0XFFFCAC12);
const Color kLightYellow=Color(0XFFF9DB9F);
const Color kOrange=Color(0XFFFFCF99);